# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: pwsh -Command {Install-Module PowerShellGet -Force}
  displayName: 'Update powershellget'
# - script: pwsh -File publish.ps1
 # displayName: 'Build and Publish Module'
  env:
    nugetapikey: $(nugetapikey)
